name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json
        continue-on-error: true

      - name: Verify Bandit report exists
        if: always()
        run: |
          if [ -f bandit-report.json ]; then
            echo "✅ Bandit report generated"
          else
            echo "⚠️ Bandit report missing, creating empty file"
            echo "{}" > bandit-report.json
          fi

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  docker_build:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    needs: sast_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker daemon setup
        run: |
          sudo mkdir -p /etc/docker
          if [ ! -f /etc/docker/daemon.json ]; then
            echo '{}' | sudo tee /etc/docker/daemon.json
            echo "✅ Created default /etc/docker/daemon.json"
          else
            echo "ℹ️ /etc/docker/daemon.json already exists"
          fi

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run Docker Scout scan
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
          docker scout quickview
          docker scout cves my-app:latest --severity CRITICAL,HIGH,MEDIUM --json > scout-report.json
        continue-on-error: true

      - name: Verify Scout report exists
        if: always()
        run: |
          if [ -f scout-report.json ]; then
            echo "✅ Scout report generated"
          else
            echo "⚠️ Scout report missing, creating empty file"
            echo "{}" > scout-report.json
          fi

      - name: Upload Scout report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: scout-report.json
